using DAL.Dtos;
using DAL.UnitOfWorks.ProvinceService;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Text;

namespace DAL.Common
{
    public static class StaticData
    {
        public static List<SelectListItem> GetProvinceSelectList()
        {
            List<SelectListItem> ProvinceSelectList = new List<SelectListItem>
            {
                new SelectListItem {Value = "01", Text = "Thành phố Hà Nội"},
                new SelectListItem {Value = "02", Text = "Tỉnh Hà Giang"},
                new SelectListItem {Value = "04", Text = "Tỉnh Cao Bằng"},
                new SelectListItem {Value = "06", Text = "Tỉnh Bắc Kạn"},
                new SelectListItem {Value = "08", Text = "Tỉnh Tuyên Quang"},
                new SelectListItem {Value = "10", Text = "Tỉnh Lào Cai"},
                new SelectListItem {Value = "11", Text = "Tỉnh Điện Biên"},
                new SelectListItem {Value = "12", Text = "Tỉnh Lai Châu"},
                new SelectListItem {Value = "14", Text = "Tỉnh Sơn La"},
                new SelectListItem {Value = "15", Text = "Tỉnh Yên Bái"},
                new SelectListItem {Value = "17", Text = "Tỉnh Hoà Bình"},
                new SelectListItem {Value = "19", Text = "Tỉnh Thái Nguyên"},
                new SelectListItem {Value = "20", Text = "Tỉnh Lạng Sơn"},
                new SelectListItem {Value = "22", Text = "Tỉnh Quảng Ninh"},
                new SelectListItem {Value = "24", Text = "Tỉnh Bắc Giang"},
                new SelectListItem {Value = "25", Text = "Tỉnh Phú Thọ"},
                new SelectListItem {Value = "26", Text = "Tỉnh Vĩnh Phúc"},
                new SelectListItem {Value = "27", Text = "Tỉnh Bắc Ninh"},
                new SelectListItem {Value = "30", Text = "Tỉnh Hải Dương"},
                new SelectListItem {Value = "31", Text = "Thành phố Hải Phòng"},
                new SelectListItem {Value = "33", Text = "Tỉnh Hưng Yên"},
                new SelectListItem {Value = "34", Text = "Tỉnh Thái Bình"},
                new SelectListItem {Value = "35", Text = "Tỉnh Hà Nam"},
                new SelectListItem {Value = "36", Text = "Tỉnh Nam Định"},
                new SelectListItem {Value = "37", Text = "Tỉnh Ninh Bình"},
                new SelectListItem {Value = "38", Text = "Tỉnh Thanh Hóa"},
                new SelectListItem {Value = "40", Text = "Tỉnh Nghệ An"},
                new SelectListItem {Value = "42", Text = "Tỉnh Hà Tĩnh"},
                new SelectListItem {Value = "44", Text = "Tỉnh Quảng Bình"},
                new SelectListItem {Value = "45", Text = "Tỉnh Quảng Trị"},
                new SelectListItem {Value = "46", Text = "Tỉnh Thừa Thiên Huế"},
                new SelectListItem {Value = "48", Text = "Thành phố Đà Nẵng"},
                new SelectListItem {Value = "49", Text = "Tỉnh Quảng Nam"},
                new SelectListItem {Value = "51", Text = "Tỉnh Quảng Ngãi"},
                new SelectListItem {Value = "52", Text = "Tỉnh Bình Định"},
                new SelectListItem {Value = "54", Text = "Tỉnh Phú Yên"},
                new SelectListItem {Value = "56", Text = "Tỉnh Khánh Hòa"},
                new SelectListItem {Value = "58", Text = "Tỉnh Ninh Thuận"},
                new SelectListItem {Value = "60", Text = "Tỉnh Bình Thuận"},
                new SelectListItem {Value = "62", Text = "Tỉnh Kon Tum"},
                new SelectListItem {Value = "64", Text = "Tỉnh Gia Lai"},
                new SelectListItem {Value = "66", Text = "Tỉnh Đắk Lắk"},
                new SelectListItem {Value = "67", Text = "Tỉnh Đắk Nông"},
                new SelectListItem {Value = "68", Text = "Tỉnh Lâm Đồng"},
                new SelectListItem {Value = "70", Text = "Tỉnh Bình Phước"},
                new SelectListItem {Value = "72", Text = "Tỉnh Tây Ninh"},
                new SelectListItem {Value = "74", Text = "Tỉnh Bình Dương"},
                new SelectListItem {Value = "75", Text = "Tỉnh Đồng Nai"},
                new SelectListItem {Value = "77", Text = "Tỉnh Bà Rịa - Vũng Tàu"},
                new SelectListItem {Value = "79", Text = "Thành phố Hồ Chí Minh"},
                new SelectListItem {Value = "80", Text = "Tỉnh Long An"},
                new SelectListItem {Value = "82", Text = "Tỉnh Tiền Giang"},
                new SelectListItem {Value = "83", Text = "Tỉnh Bến Tre"},
                new SelectListItem {Value = "84", Text = "Tỉnh Trà Vinh"},
                new SelectListItem {Value = "86", Text = "Tỉnh Vĩnh Long"},
                new SelectListItem {Value = "87", Text = "Tỉnh Đồng Tháp"},
                new SelectListItem {Value = "89", Text = "Tỉnh An Giang"},
                new SelectListItem {Value = "91", Text = "Tỉnh Kiên Giang"},
                new SelectListItem {Value = "92", Text = "Thành phố Cần Thơ"},
                new SelectListItem {Value = "93", Text = "Tỉnh Hậu Giang"},
                new SelectListItem {Value = "94", Text = "Tỉnh Sóc Trăng"},
                new SelectListItem {Value = "95", Text = "Tỉnh Bạc Liêu"},
                new SelectListItem {Value = "96", Text = "Tỉnh Cà Mau"},
            };
            return ProvinceSelectList;
        }

        public static List<ProvinceDto> GetProvincesList()
        {
            List<ProvinceDto> ProvinceList = new List<ProvinceDto>
            {
                new ProvinceDto {ProvinceCode = "01", Name = "Thành phố Hà Nội"},
                new ProvinceDto {ProvinceCode = "02", Name = "Tỉnh Hà Giang"},
                new ProvinceDto {ProvinceCode = "04", Name = "Tỉnh Cao Bằng"},
                new ProvinceDto {ProvinceCode = "06", Name = "Tỉnh Bắc Kạn"},
                new ProvinceDto {ProvinceCode = "08", Name = "Tỉnh Tuyên Quang"},
                new ProvinceDto {ProvinceCode = "10", Name = "Tỉnh Lào Cai"},
                new ProvinceDto {ProvinceCode = "11", Name = "Tỉnh Điện Biên"},
                new ProvinceDto {ProvinceCode = "12", Name = "Tỉnh Lai Châu"},
                new ProvinceDto {ProvinceCode = "14", Name = "Tỉnh Sơn La"},
                new ProvinceDto {ProvinceCode = "15", Name = "Tỉnh Yên Bái"},
                new ProvinceDto {ProvinceCode = "17", Name = "Tỉnh Hoà Bình"},
                new ProvinceDto {ProvinceCode = "19", Name = "Tỉnh Thái Nguyên"},
                new ProvinceDto {ProvinceCode = "20", Name = "Tỉnh Lạng Sơn"},
                new ProvinceDto {ProvinceCode = "22", Name = "Tỉnh Quảng Ninh"},
                new ProvinceDto {ProvinceCode = "24", Name = "Tỉnh Bắc Giang"},
                new ProvinceDto {ProvinceCode = "25", Name = "Tỉnh Phú Thọ"},
                new ProvinceDto {ProvinceCode = "26", Name = "Tỉnh Vĩnh Phúc"},
                new ProvinceDto {ProvinceCode = "27", Name = "Tỉnh Bắc Ninh"},
                new ProvinceDto {ProvinceCode = "30", Name = "Tỉnh Hải Dương"},
                new ProvinceDto {ProvinceCode = "31", Name = "Thành phố Hải Phòng"},
                new ProvinceDto {ProvinceCode = "33", Name = "Tỉnh Hưng Yên"},
                new ProvinceDto {ProvinceCode = "34", Name = "Tỉnh Thái Bình"},
                new ProvinceDto {ProvinceCode = "35", Name = "Tỉnh Hà Nam"},
                new ProvinceDto {ProvinceCode = "36", Name = "Tỉnh Nam Định"},
                new ProvinceDto {ProvinceCode = "37", Name = "Tỉnh Ninh Bình"},
                new ProvinceDto {ProvinceCode = "38", Name = "Tỉnh Thanh Hóa"},
                new ProvinceDto {ProvinceCode = "40", Name = "Tỉnh Nghệ An"},
                new ProvinceDto {ProvinceCode = "42", Name = "Tỉnh Hà Tĩnh"},
                new ProvinceDto {ProvinceCode = "44", Name = "Tỉnh Quảng Bình"},
                new ProvinceDto {ProvinceCode = "45", Name = "Tỉnh Quảng Trị"},
                new ProvinceDto {ProvinceCode = "46", Name = "Tỉnh Thừa Thiên Huế"},
                new ProvinceDto {ProvinceCode = "48", Name = "Thành phố Đà Nẵng"},
                new ProvinceDto {ProvinceCode = "49", Name = "Tỉnh Quảng Nam"},
                new ProvinceDto {ProvinceCode = "51", Name = "Tỉnh Quảng Ngãi"},
                new ProvinceDto {ProvinceCode = "52", Name = "Tỉnh Bình Định"},
                new ProvinceDto {ProvinceCode = "54", Name = "Tỉnh Phú Yên"},
                new ProvinceDto {ProvinceCode = "56", Name = "Tỉnh Khánh Hòa"},
                new ProvinceDto {ProvinceCode = "58", Name = "Tỉnh Ninh Thuận"},
                new ProvinceDto {ProvinceCode = "60", Name = "Tỉnh Bình Thuận"},
                new ProvinceDto {ProvinceCode = "62", Name = "Tỉnh Kon Tum"},
                new ProvinceDto {ProvinceCode = "64", Name = "Tỉnh Gia Lai"},
                new ProvinceDto {ProvinceCode = "66", Name = "Tỉnh Đắk Lắk"},
                new ProvinceDto {ProvinceCode = "67", Name = "Tỉnh Đắk Nông"},
                new ProvinceDto {ProvinceCode = "68", Name = "Tỉnh Lâm Đồng"},
                new ProvinceDto {ProvinceCode = "70", Name = "Tỉnh Bình Phước"},
                new ProvinceDto {ProvinceCode = "72", Name = "Tỉnh Tây Ninh"},
                new ProvinceDto {ProvinceCode = "74", Name = "Tỉnh Bình Dương"},
                new ProvinceDto {ProvinceCode = "75", Name = "Tỉnh Đồng Nai"},
                new ProvinceDto {ProvinceCode = "77", Name = "Tỉnh Bà Rịa - Vũng Tàu"},
                new ProvinceDto {ProvinceCode = "79", Name = "Thành phố Hồ Chí Minh"},
                new ProvinceDto {ProvinceCode = "80", Name = "Tỉnh Long An"},
                new ProvinceDto {ProvinceCode = "82", Name = "Tỉnh Tiền Giang"},
                new ProvinceDto {ProvinceCode = "83", Name = "Tỉnh Bến Tre"},
                new ProvinceDto {ProvinceCode = "84", Name = "Tỉnh Trà Vinh"},
                new ProvinceDto {ProvinceCode = "86", Name = "Tỉnh Vĩnh Long"},
                new ProvinceDto {ProvinceCode = "87", Name = "Tỉnh Đồng Tháp"},
                new ProvinceDto {ProvinceCode = "89", Name = "Tỉnh An Giang"},
                new ProvinceDto {ProvinceCode = "91", Name = "Tỉnh Kiên Giang"},
                new ProvinceDto {ProvinceCode = "92", Name = "Thành phố Cần Thơ"},
                new ProvinceDto {ProvinceCode = "93", Name = "Tỉnh Hậu Giang"},
                new ProvinceDto {ProvinceCode = "94", Name = "Tỉnh Sóc Trăng"},
                new ProvinceDto {ProvinceCode = "95", Name = "Tỉnh Bạc Liêu"},
                new ProvinceDto {ProvinceCode = "96", Name = "Tỉnh Cà Mau"},
            };
            return ProvinceList;
        }
    }
}
